name: Automation Tests Suite

# The workflow will start for every PR against master branch
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  automation_test_cases:
    name: Automation Tests Suite
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Clone edx-app-test repository
        run: |
          git clone https://github.com/openedx/edx-app-test.git

      - name: Run E2E
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: Nexus 4
          api-level: 21
          arch: x86
          target: google_apis
          disable-animations: true
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
