name: Automation Tests Suite

# The workflow will start for every PR against master branch
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  automation_test_cases:
    name: Automation Tests Suite
    runs-on: macos-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Clone edx-app-test repository
        run: |
          git clone https://github.com/openedx/edx-app-test.git

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run E2E
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: Nexus 4
          api-level: 21
          arch: x86
          target: google_apis
          disable-animations: true
          force-avd-creation: false
          script: |
            echo "test emulator"
