API_HOST_URL: 'http://beta.eliteu.cn' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
PLATFORM_NAME: 'EliteU'
PLATFORM_NAME_ZH: '英荔教育'
PLATFORM_DESTINATION_NAME: 'example.com'
FEEDBACK_EMAIL_ADDRESS: '444239383@qq.com'
DEBUG: true
NEW_LOGISTRATION_ENABLED: true
USER_PROFILES_ENABLED: true
COURSE_SHARING_ENABLED: true
DISCUSSIONS_ENABLED: true
PUSH_NOTIFICATIONS: true
CERTIFICATES_ENABLED: true
NEW_LOGISTRATION_ENABLED: true
BADGES_ENABLED: true
COURSE_SHARING_ENABLED: true
APP_REVIEWS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
VIDEO_TRANSCRIPT_ENABLED: true
COURSE_ENROLLMENT: {"TYPE": "NATIVE"}



